"""公共常量与工具（PR7 reason_code 等）"""
from src.common.reason_codes import (  # noqa: F401
    INVALID_SIGNATURE,
    MISSING_SIGNATURE,
    MALFORMED_PAYLOAD,
    INVALID_CONFIGURATION,
    MISSING_STRATEGY_ID,
    CONFIG_UNAVAILABLE,
    SECRET_NOT_CONFIGURED,
    SKIPPED_NOT_READY,
    SKIPPED_ALREADY_CLAIMED,
    RISK_REJECTED,
    EXCHANGE_TRANSIENT_ERROR,
    RETRY_SCHEDULED,
    RETRY_EXHAUSTED,
    INTERNAL_ERROR,
    SUCCESS_FILLED,
    ORDER_REJECTED,
)
