"""
执行事件类型常量（PR8：audit/events 落库）
与 reason_code 配合使用，仅存稳定枚举值。
"""
CLAIMED = "CLAIMED"
CONFIG_SNAPSHOT = "CONFIG_SNAPSHOT"
RISK_CHECK_STARTED = "RISK_CHECK_STARTED"
RISK_PASSED = "RISK_PASSED"
RISK_REJECTED = "RISK_REJECTED"
ORDER_SUBMIT_STARTED = "ORDER_SUBMIT_STARTED"
ORDER_SUBMIT_OK = "ORDER_SUBMIT_OK"
ORDER_SUBMIT_FAILED = "ORDER_SUBMIT_FAILED"
RETRY_SCHEDULED = "RETRY_SCHEDULED"
FINAL_FAILED = "FINAL_FAILED"
FILLED = "FILLED"
# PR12 工程级整改：OrderManager 行为审计
ORDER_CANCELLED = "ORDER_CANCELLED"
ORDER_SYNCED = "ORDER_SYNCED"
# PR13：安全阀与审计
DRY_RUN = "DRY_RUN"
CIRCUIT_OPENED = "CIRCUIT_OPENED"
CIRCUIT_CLOSED = "CIRCUIT_CLOSED"
# PR16：运维人工重置断路器（受控脚本写入，不含 secret）
CIRCUIT_RESET_BY_OPERATOR = "CIRCUIT_RESET_BY_OPERATOR"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
# PR15a：真实 HTTP 通信审计（get_order/cancel_order，不含 secret）
OKX_HTTP_GET_ORDER = "OKX_HTTP_GET_ORDER"
OKX_HTTP_CANCEL_ORDER = "OKX_HTTP_CANCEL_ORDER"
# PR15b：create_order 通信审计 + 重试审计（仅 action/http_status/okx_code/request_id/attempt）
OKX_HTTP_CREATE_ORDER = "OKX_HTTP_CREATE_ORDER"
OKX_HTTP_RETRY = "OKX_HTTP_RETRY"
# PR15b：订单业务审计（与 OKX_HTTP_* 职责分离，不含 secret/header）
ORDER_SUBMITTED = "ORDER_SUBMITTED"  # create_order 成功返回 exchange_order_id（与 ORDER_SUBMIT_OK 语义一致）
ORDER_REJECTED = "ORDER_REJECTED"    # 交易所拒单/参数错误/鉴权失败
# Phase1.1 C2：阶段3 拿不到锁时，交易所已成功但未落库，可被对账/恢复识别
PENDING_EXCHANGE_ACK_NOT_COMMITTED = "PENDING_EXCHANGE_ACK_NOT_COMMITTED"
