"""
统一 reason_code 常量（PR7：HTTP 响应、执行结果、DB last_error、日志）
全大写 snake_case，贯穿全链路。
"""
# Webhook / 验签 / 配置
INVALID_SIGNATURE = "INVALID_SIGNATURE"
MISSING_SIGNATURE = "MISSING_SIGNATURE"
MALFORMED_PAYLOAD = "MALFORMED_PAYLOAD"
INVALID_CONFIGURATION = "INVALID_CONFIGURATION"
# PR10 P2-2：类别级 reason_code，便于快速定位
INVALID_WEBHOOK_CONFIGURATION = "INVALID_WEBHOOK_CONFIGURATION"
INVALID_DATABASE_CONFIGURATION = "INVALID_DATABASE_CONFIGURATION"
INVALID_EXECUTION_CONFIGURATION = "INVALID_EXECUTION_CONFIGURATION"
INVALID_RISK_CONFIGURATION = "INVALID_RISK_CONFIGURATION"
MISSING_STRATEGY_ID = "MISSING_STRATEGY_ID"
# PR11：多 strategy 校验
STRATEGY_NOT_FOUND = "STRATEGY_NOT_FOUND"
STRATEGY_DISABLED = "STRATEGY_DISABLED"
CONFIG_UNAVAILABLE = "CONFIG_UNAVAILABLE"
# PR13：账户/交易所显式绑定
INVALID_ACCOUNT_CONFIGURATION = "INVALID_ACCOUNT_CONFIGURATION"
MISSING_EXCHANGE_PROFILE = "MISSING_EXCHANGE_PROFILE"
MISSING_ACCOUNT = "MISSING_ACCOUNT"
ACCOUNT_EXCHANGE_MISMATCH = "ACCOUNT_EXCHANGE_MISMATCH"
# PR14a：实盘门禁（live_enabled=true 时缺显式配置）
LIVE_GATE_MISSING_ACCOUNT_ID = "LIVE_GATE_MISSING_ACCOUNT_ID"
LIVE_GATE_MISSING_EXCHANGE_PROFILE_ID = "LIVE_GATE_MISSING_EXCHANGE_PROFILE_ID"
LIVE_GATE_ACCOUNT_NOT_FOUND = "LIVE_GATE_ACCOUNT_NOT_FOUND"
LIVE_GATE_EXCHANGE_PROFILE_NOT_FOUND = "LIVE_GATE_EXCHANGE_PROFILE_NOT_FOUND"
LIVE_GATE_ACCOUNT_EXCHANGE_MISMATCH = "LIVE_GATE_ACCOUNT_EXCHANGE_MISMATCH"
SECRET_NOT_CONFIGURED = "SECRET_NOT_CONFIGURED"
# 封版：多策略 position 不可逆性
MULTI_STRATEGY_POSITION_DOWNGRADE_FORBIDDEN = "MULTI_STRATEGY_POSITION_DOWNGRADE_FORBIDDEN"

# 执行层：跳过
SKIPPED_NOT_READY = "SKIPPED_NOT_READY"  # next_run_at 未到 / 任务不可执行
SKIPPED_ALREADY_CLAIMED = "SKIPPED_ALREADY_CLAIMED"  # 并发抢占失败

# 执行层：失败
RISK_REJECTED = "RISK_REJECTED"
COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
DUPLICATE_DIRECTION = "DUPLICATE_DIRECTION"
POSITION_LIMIT_EXCEEDED = "POSITION_LIMIT_EXCEEDED"
ORDER_SIZE_EXCEEDED = "ORDER_SIZE_EXCEEDED"
# PR15c：资金/账户级风控
INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
TOTAL_EXPOSURE_EXCEEDED = "TOTAL_EXPOSURE_EXCEEDED"
EXCHANGE_TRANSIENT_ERROR = "EXCHANGE_TRANSIENT_ERROR"
RETRY_SCHEDULED = "RETRY_SCHEDULED"
RETRY_EXHAUSTED = "RETRY_EXHAUSTED"
ORDER_REJECTED = "ORDER_REJECTED"
INTERNAL_ERROR = "INTERNAL_ERROR"
# PR13：安全阀
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
CIRCUIT_OPEN = "CIRCUIT_OPEN"

# 执行层：成功（paper）
SUCCESS_FILLED = "SUCCESS_FILLED"

# PR14b：OKX adapter 错误分类（可追溯、可测试）
OKX_AUTH_FAILED = "OKX_AUTH_FAILED"
OKX_RATE_LIMIT = "OKX_RATE_LIMIT"
OKX_TEMP_UNAVAILABLE = "OKX_TEMP_UNAVAILABLE"
OKX_ORDER_REJECTED = "OKX_ORDER_REJECTED"
OKX_SECRET_MISSING = "OKX_SECRET_MISSING"
# PR15a：live 门禁与错误分类
OKX_LIVE_FORBIDDEN = "OKX_LIVE_FORBIDDEN"
OKX_BAD_REQUEST = "OKX_BAD_REQUEST"

# PR16：多重 Live 门禁（仅当 is_live_endpoint=True 时校验；demo rehearsal 不触发，不污染）
LIVE_GATE_ALLOW_REAL_TRADING_OFF = "LIVE_GATE_ALLOW_REAL_TRADING_OFF"
LIVE_GATE_ALLOWLIST_NOT_MATCHED = "LIVE_GATE_ALLOWLIST_NOT_MATCHED"
LIVE_GATE_CONFIRM_TOKEN_MISSING = "LIVE_GATE_CONFIRM_TOKEN_MISSING"  # 配置或 env 缺失 token
LIVE_GATE_CONFIRM_TOKEN_MISMATCH = "LIVE_GATE_CONFIRM_TOKEN_MISMATCH"  # 两端 token 不匹配
LIVE_GATE_REAL_LIVE_FORBIDDEN = "LIVE_GATE_REAL_LIVE_FORBIDDEN"  # PR16 仍不允许实盘
# PR16c：live_allowlist_symbols 中每个 symbol 须在 qty_precision_by_symbol 中显式配置（启动 fail-fast）
LIVE_GATE_SYMBOL_PRECISION_MISSING = "LIVE_GATE_SYMBOL_PRECISION_MISSING"
LIVE_GATE_SYMBOL_NOT_ALLOWED = "LIVE_GATE_SYMBOL_NOT_ALLOWED"  # is_live_endpoint 时 symbol 不在 live_allowlist_symbols

# PR17a：Live 路径门禁与预演
LIVE_GATE_ACCOUNT_NOT_ALLOWED = "LIVE_GATE_ACCOUNT_NOT_ALLOWED"  # account_id 不在 live_allowlist_accounts
LIVE_GATE_ALLOWLIST_ACCOUNTS_REQUIRED = "LIVE_GATE_ALLOWLIST_ACCOUNTS_REQUIRED"  # live 路径下 allowlist_accounts 必须非空
LIVE_GATE_ALLOWLIST_SYMBOLS_REQUIRED = "LIVE_GATE_ALLOWLIST_SYMBOLS_REQUIRED"  # live 路径下 allowlist_symbols 必须非空
LIVE_GATE_PR17A_ORDER_DISABLED = "LIVE_GATE_PR17A_ORDER_DISABLED"  # PR17a 阶段：门禁全过仍禁止 live 下单（PR17b 已移除）
LIVE_GATE_LIVE_ENABLED_REQUIRED = "LIVE_GATE_LIVE_ENABLED_REQUIRED"  # PR17b：is_live_endpoint 时 live_enabled 必须 true

# PR17b：极小额 live 风险限制（超限拒绝，不触发 HTTP）
LIVE_RISK_NOTIONAL_EXCEEDED = "LIVE_RISK_NOTIONAL_EXCEEDED"
LIVE_RISK_DAILY_LIMIT = "LIVE_RISK_DAILY_LIMIT"
LIVE_RISK_HOURLY_LIMIT = "LIVE_RISK_HOURLY_LIMIT"
LIVE_RISK_QTY_EXCEEDED = "LIVE_RISK_QTY_EXCEEDED"
LIVE_RISK_PRICE_UNAVAILABLE = "LIVE_RISK_PRICE_UNAVAILABLE"

# Phase1.1 C2：下单路径互斥保护（ReconcileLock acquire 失败）
RECONCILE_LOCK_NOT_ACQUIRED = "RECONCILE_LOCK_NOT_ACQUIRED"
# C2 阶段3 拿不到锁：交易所已成功，本地 PENDING_EXCHANGE 可恢复，不可丢单
PENDING_EXCHANGE_ACK_NOT_COMMITTED = "PENDING_EXCHANGE_ACK_NOT_COMMITTED"

# PR16：参数精度与数量校验（本地拒绝，不触发 HTTP）
ORDER_PARAM_INVALID = "ORDER_PARAM_INVALID"
ORDER_QTY_ZERO_OR_NEGATIVE = "ORDER_QTY_ZERO_OR_NEGATIVE"
ORDER_QTY_PRECISION_EXCEEDED = "ORDER_QTY_PRECISION_EXCEEDED"
ORDER_QTY_NAN_INF = "ORDER_QTY_NAN_INF"
ORDER_MARKET_NOTIONAL_EXCEEDED = "ORDER_MARKET_NOTIONAL_EXCEEDED"
